# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBSG4aemEUmvGyDI3BAW0GcYvre--inR
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the trained model and scaler
model = pickle.load(open('/log_reg_model.pkl', 'rb'))
scaler = pickle.load(open('/scaler.pkl', 'rb'))

st.title("Diabetes Prediction App")
st.write("Enter the following details to predict if a person is likely to have diabetes:")

# User inputs
Pregnancies = st.number_input("Pregnancies", 0, 20, 1)
Glucose = st.number_input("Glucose Level", 0, 200, 100)
Insulin = st.number_input("Insulin Level", 0, 900, 80)
BMI = st.number_input("BMI", 0.0, 70.0, 25.0)
DiabetesPedigreeFunction = st.number_input("Diabetes Pedigree Function", 0.0, 3.0, 0.5)
Age = st.number_input("Age", 1, 120, 25)

# Prediction button
if st.button("Predict"):
    input_data = np.array([[Pregnancies, Glucose, Insulin,BMI, DiabetesPedigreeFunction, Age]])
    # Apply the same scaling used during training
    scaled_input = scaler.transform(input_data)
    # Predict using the trained model
    prediction = model.predict(scaled_input)
    prob = model.predict_proba(scaled_input)[0][1]  # optional: probability for class 1

    # Output
    result = "Positive (Diabetic)" if prediction[0] == 1 else "Negative (Non-Diabetic)"
    st.success(f"The model predicts: {result}")
    st.write(f"Prediction probability (Positive class): {prob:.2f}")

